default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: qweqwe
  host: localhost

development:
  <<: *default
  database: format-odin_development

test:
  <<: *default
  database: format-odin_test

production:
  <<: *default
  database: format-odin_production