default: &default
  adapter: postgresql
  encoding: utf8
  username: achernik
  password:

development:
  <<: *default
  database: formatodin_development

test:
  <<: *default
  database: formatodin_test

production:
  <<: *default
  database: formatodin_production